// ============================================================
// Persona overview seed (discussion #265, issue #271): the data the four persona
// views need, and the relations between the personas.
//
//   patient P1 (Maria Schmidt, the patient1 login) -TREATED_AT-> AlphaKlinik Berlin (holder)
//     -HAS_ENCOUNTER-> one laboratory visit per measurement date
//     -HAS_OBSERVATION-> 48 LOINC-coded measurements with reference ranges
//     -HAS_CONDITION / HAS_MEDICATION_REQUEST-> her record
//     -GAVE_CONSENT-> PatientConsent -FOR_STUDY-> ResearchStudy
//   ResearchStudy <-CONDUCTS- Participant (PharmaCo, IRS, MedReg)
//     -HAS_ENROLMENT-> StudyEnrolment, one per quarter
//   TransferEvent, one per access, twelve months, per consumer and dataset
//     -READ-> Patient for the reads that touched P1's record (Art. 8 log)
//     -REQUESTED_BY-> consumer, -PROVIDED_BY-> AlphaKlinik, -ACCESSED-> dataset,
//     -UNDER_PERMIT-> HDABApproval (issued by MedReg DE / IRS)
//   VerifiableCredential (quality label) -HAS_ASSESSMENT-> QualityAssessment
//     -ASSESSES-> dataset, one per quarter
//
// Generated by scripts/generate-persona-overview-seed.py. Do not edit by
// hand; change the generator and run it. Fictional data only. Idempotent
// MERGE throughout. Run after seed-compliance-matrix.cypher.
// ============================================================

// ── 1. The demo patient, treated at AlphaKlinik Berlin ──────────────────────
MERGE (p:Patient {resourceId: 'P1'})
SET p.id = 'P1',
    p.name = 'Maria Schmidt',
    p.gender = 'female',
    p.birthDate = date('1979-03-15'),
    p.city = 'Berlin',
    p.country = 'DE',
    p.demo = true,
    p.fictional = true
WITH p
MATCH (holder:Participant {participantId: 'did:web:alpha-klinik.de:participant'})
MERGE (p)-[:TREATED_AT]->(holder)
WITH p
MATCH (ds:HealthDataset {datasetId: 'dataset:synthea-fhir-r4-mvd'})
MERGE (p)-[:FROM_DATASET]->(ds);

// ── 2. Her diagnoses and medications (as in patient_profile_patient1.json) ──
MATCH (p:Patient {resourceId: 'P1'})
UNWIND [
  {id: 'cond-p1-73211009', code: '73211009', system: 'http://snomed.info/sct', display: 'Diabetes mellitus type 2', onset: '2018-04-10'},
  {id: 'cond-p1-38341003', code: '38341003', system: 'http://snomed.info/sct', display: 'Hypertension', onset: '2015-11-02'},
  {id: 'cond-p1-73595000', code: '73595000', system: 'http://snomed.info/sct', display: 'Stress (finding)', onset: '2020-01-15'},
  {id: 'cond-p1-E11.9', code: 'E11.9', system: 'http://hl7.org/fhir/sid/icd-10', display: 'T2D without complications', onset: '2018-04-10'},
  {id: 'cond-p1-414916001', code: '414916001', system: 'http://snomed.info/sct', display: 'Obesity (BMI 31.2)', onset: '2017-06-20'},
  {id: 'cond-p1-271825005', code: '271825005', system: 'http://snomed.info/sct', display: 'Respiratory distress', onset: '2021-03-08'},
  {id: 'cond-p1-40055000', code: '40055000', system: 'http://snomed.info/sct', display: 'Chronic sinusitis', onset: '2013-09-14'},
  {id: 'cond-p1-195967001', code: '195967001', system: 'http://snomed.info/sct', display: 'Asthma', onset: '2009-02-27'}
] AS c
MERGE (cond:Condition {resourceId: c.id})
SET cond.code = c.code,
    cond.codeSystem = c.system,
    cond.display = c.display,
    cond.name = c.display,
    cond.clinicalStatus = 'active',
    cond.onsetDate = c.onset,
    cond.fictional = true
MERGE (p)-[:HAS_CONDITION]->(cond);

MATCH (p:Patient {resourceId: 'P1'})
UNWIND [
  {id: 'med-p1-860975', code: '860975', display: 'Metformin 500 mg oral tablet', since: '2018-04-10'},
  {id: 'med-p1-197361', code: '197361', display: 'Lisinopril 10 mg oral tablet', since: '2015-11-02'},
  {id: 'med-p1-308460', code: '308460', display: 'Salbutamol 100 mcg inhaler', since: '2009-02-27'},
  {id: 'med-p1-209459', code: '209459', display: 'Atorvastatin 20 mg oral tablet', since: '2024-09-12'}
] AS m
MERGE (med:MedicationRequest {resourceId: m.id})
SET med.medicationCode = m.code,
    med.code = m.code,
    med.codeSystem = 'http://www.nlm.nih.gov/research/umls/rxnorm',
    med.display = m.display,
    med.name = m.display,
    med.status = 'active',
    med.intent = 'order',
    med.date = m.since,
    med.fictional = true
MERGE (p)-[:HAS_MEDICATION_REQUEST]->(med);

// ── 2b. Her visits: one laboratory visit per measurement date ─────────────
MATCH (p:Patient {resourceId: 'P1'})
UNWIND [
  {id: 'enc-p1-2024-09-12', at: '2024-09-12', n: 1},
  {id: 'enc-p1-2025-01-20', at: '2025-01-20', n: 2},
  {id: 'enc-p1-2025-05-15', at: '2025-05-15', n: 3},
  {id: 'enc-p1-2025-09-18', at: '2025-09-18', n: 4},
  {id: 'enc-p1-2026-02-10', at: '2026-02-10', n: 5},
  {id: 'enc-p1-2026-08-21', at: '2026-08-21', n: 6}
] AS e
MERGE (enc:Encounter {resourceId: e.id})
SET enc.name = 'Laboratory visit ' + toString(e.n) + ' of 6',
    enc.display = 'Laboratory visit, AlphaKlinik Berlin (fictional)',
    enc.class = 'ambulatory',
    enc.status = 'finished',
    enc.date = e.at + 'T08:00:00Z',
    enc.period = e.at,
    enc.serviceProvider = 'AlphaKlinik Berlin',
    enc.fictional = true
MERGE (p)-[:HAS_ENCOUNTER]->(enc);

// ── 3. Her measurements: 8 LOINC parameters, 6 visits, lab reference ranges ─
// The values behind the risk scores of the profile: HbA1c and glucose drift
// up, LDL falls under atorvastatin, blood pressure improves under lisinopril,
// eGFR slips below the range. Art. 14 priority category: laboratory results.
MATCH (p:Patient {resourceId: 'P1'})
UNWIND [
  {id: 'obs-p1-4548-4-2024-09-12', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 6.4, low: 4.0, high: 6.0, category: 'laboratory', at: '2024-09-12'},
  {id: 'obs-p1-4548-4-2025-01-20', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 6.6, low: 4.0, high: 6.0, category: 'laboratory', at: '2025-01-20'},
  {id: 'obs-p1-4548-4-2025-05-15', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 6.9, low: 4.0, high: 6.0, category: 'laboratory', at: '2025-05-15'},
  {id: 'obs-p1-4548-4-2025-09-18', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 7.1, low: 4.0, high: 6.0, category: 'laboratory', at: '2025-09-18'},
  {id: 'obs-p1-4548-4-2026-02-10', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 7.3, low: 4.0, high: 6.0, category: 'laboratory', at: '2026-02-10'},
  {id: 'obs-p1-4548-4-2026-08-21', code: '4548-4', display: 'Hemoglobin A1c/Hemoglobin.total in Blood', unit: '%', value: 7.6, low: 4.0, high: 6.0, category: 'laboratory', at: '2026-08-21'},
  {id: 'obs-p1-2339-0-2024-09-12', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 118, low: 70, high: 99, category: 'laboratory', at: '2024-09-12'},
  {id: 'obs-p1-2339-0-2025-01-20', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 124, low: 70, high: 99, category: 'laboratory', at: '2025-01-20'},
  {id: 'obs-p1-2339-0-2025-05-15', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 131, low: 70, high: 99, category: 'laboratory', at: '2025-05-15'},
  {id: 'obs-p1-2339-0-2025-09-18', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 129, low: 70, high: 99, category: 'laboratory', at: '2025-09-18'},
  {id: 'obs-p1-2339-0-2026-02-10', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 138, low: 70, high: 99, category: 'laboratory', at: '2026-02-10'},
  {id: 'obs-p1-2339-0-2026-08-21', code: '2339-0', display: 'Glucose [Mass/volume] in Blood', unit: 'mg/dL', value: 142, low: 70, high: 99, category: 'laboratory', at: '2026-08-21'},
  {id: 'obs-p1-2089-1-2024-09-12', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 158, low: 0, high: 116, category: 'laboratory', at: '2024-09-12'},
  {id: 'obs-p1-2089-1-2025-01-20', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 149, low: 0, high: 116, category: 'laboratory', at: '2025-01-20'},
  {id: 'obs-p1-2089-1-2025-05-15', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 141, low: 0, high: 116, category: 'laboratory', at: '2025-05-15'},
  {id: 'obs-p1-2089-1-2025-09-18', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 136, low: 0, high: 116, category: 'laboratory', at: '2025-09-18'},
  {id: 'obs-p1-2089-1-2026-02-10', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 134, low: 0, high: 116, category: 'laboratory', at: '2026-02-10'},
  {id: 'obs-p1-2089-1-2026-08-21', code: '2089-1', display: 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 132, low: 0, high: 116, category: 'laboratory', at: '2026-08-21'},
  {id: 'obs-p1-2093-3-2024-09-12', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 232, low: 0, high: 200, category: 'laboratory', at: '2024-09-12'},
  {id: 'obs-p1-2093-3-2025-01-20', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 221, low: 0, high: 200, category: 'laboratory', at: '2025-01-20'},
  {id: 'obs-p1-2093-3-2025-05-15', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 214, low: 0, high: 200, category: 'laboratory', at: '2025-05-15'},
  {id: 'obs-p1-2093-3-2025-09-18', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 208, low: 0, high: 200, category: 'laboratory', at: '2025-09-18'},
  {id: 'obs-p1-2093-3-2026-02-10', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 206, low: 0, high: 200, category: 'laboratory', at: '2026-02-10'},
  {id: 'obs-p1-2093-3-2026-08-21', code: '2093-3', display: 'Cholesterol [Mass/volume] in Serum or Plasma', unit: 'mg/dL', value: 205, low: 0, high: 200, category: 'laboratory', at: '2026-08-21'},
  {id: 'obs-p1-8480-6-2024-09-12', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 146, low: 100, high: 130, category: 'vital-signs', at: '2024-09-12'},
  {id: 'obs-p1-8480-6-2025-01-20', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 142, low: 100, high: 130, category: 'vital-signs', at: '2025-01-20'},
  {id: 'obs-p1-8480-6-2025-05-15', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 139, low: 100, high: 130, category: 'vital-signs', at: '2025-05-15'},
  {id: 'obs-p1-8480-6-2025-09-18', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 141, low: 100, high: 130, category: 'vital-signs', at: '2025-09-18'},
  {id: 'obs-p1-8480-6-2026-02-10', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 137, low: 100, high: 130, category: 'vital-signs', at: '2026-02-10'},
  {id: 'obs-p1-8480-6-2026-08-21', code: '8480-6', display: 'Systolic blood pressure', unit: 'mm[Hg]', value: 138, low: 100, high: 130, category: 'vital-signs', at: '2026-08-21'},
  {id: 'obs-p1-8462-4-2024-09-12', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 92, low: 60, high: 85, category: 'vital-signs', at: '2024-09-12'},
  {id: 'obs-p1-8462-4-2025-01-20', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 90, low: 60, high: 85, category: 'vital-signs', at: '2025-01-20'},
  {id: 'obs-p1-8462-4-2025-05-15', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 88, low: 60, high: 85, category: 'vital-signs', at: '2025-05-15'},
  {id: 'obs-p1-8462-4-2025-09-18', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 89, low: 60, high: 85, category: 'vital-signs', at: '2025-09-18'},
  {id: 'obs-p1-8462-4-2026-02-10', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 86, low: 60, high: 85, category: 'vital-signs', at: '2026-02-10'},
  {id: 'obs-p1-8462-4-2026-08-21', code: '8462-4', display: 'Diastolic blood pressure', unit: 'mm[Hg]', value: 87, low: 60, high: 85, category: 'vital-signs', at: '2026-08-21'},
  {id: 'obs-p1-39156-5-2024-09-12', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 30.4, low: 18.5, high: 25.0, category: 'vital-signs', at: '2024-09-12'},
  {id: 'obs-p1-39156-5-2025-01-20', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 30.8, low: 18.5, high: 25.0, category: 'vital-signs', at: '2025-01-20'},
  {id: 'obs-p1-39156-5-2025-05-15', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 31.0, low: 18.5, high: 25.0, category: 'vital-signs', at: '2025-05-15'},
  {id: 'obs-p1-39156-5-2025-09-18', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 31.2, low: 18.5, high: 25.0, category: 'vital-signs', at: '2025-09-18'},
  {id: 'obs-p1-39156-5-2026-02-10', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 31.2, low: 18.5, high: 25.0, category: 'vital-signs', at: '2026-02-10'},
  {id: 'obs-p1-39156-5-2026-08-21', code: '39156-5', display: 'Body mass index (BMI) [Ratio]', unit: 'kg/m2', value: 31.2, low: 18.5, high: 25.0, category: 'vital-signs', at: '2026-08-21'},
  {id: 'obs-p1-33914-3-2024-09-12', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 96, low: 90, high: null, category: 'laboratory', at: '2024-09-12'},
  {id: 'obs-p1-33914-3-2025-01-20', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 94, low: 90, high: null, category: 'laboratory', at: '2025-01-20'},
  {id: 'obs-p1-33914-3-2025-05-15', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 93, low: 90, high: null, category: 'laboratory', at: '2025-05-15'},
  {id: 'obs-p1-33914-3-2025-09-18', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 91, low: 90, high: null, category: 'laboratory', at: '2025-09-18'},
  {id: 'obs-p1-33914-3-2026-02-10', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 90, low: 90, high: null, category: 'laboratory', at: '2026-02-10'},
  {id: 'obs-p1-33914-3-2026-08-21', code: '33914-3', display: 'Glomerular filtration rate/1.73 sq M.predicted', unit: 'mL/min/{1.73_m2}', value: 88, low: 90, high: null, category: 'laboratory', at: '2026-08-21'}
] AS o
MERGE (obs:Observation {resourceId: o.id})
SET obs.code = o.code,
    obs.codeSystem = 'http://loinc.org',
    obs.display = o.display,
    obs.name = o.display + ' ' + toString(o.value) + ' ' + o.unit,
    obs.status = 'final',
    obs.category = o.category,
    obs.valueQuantity = o.value,
    obs.value = o.value,
    obs.unit = o.unit,
    obs.valueUnit = o.unit,
    obs.referenceLow = o.low,
    obs.referenceHigh = o.high,
    obs.referenceText = CASE WHEN o.high IS NULL THEN '> ' + toString(o.low) ELSE toString(o.low) + ' - ' + toString(o.high) END + ' ' + o.unit + ' (as printed on the report)',
    obs.effectiveDate = date(o.at),
    obs.dateTime = o.at + 'T08:30:00Z',
    obs.performer = 'AlphaKlinik Berlin, Zentrallabor (fictional)',
    obs.fictional = true
MERGE (p)-[:HAS_OBSERVATION]->(obs)
WITH p, obs, o
MATCH (enc:Encounter {resourceId: 'enc-p1-' + o.at})
MERGE (obs)-[:PART_OF]->(enc)
WITH obs, o
MERGE (lc:LoincCode {loincNumber: o.code})
  ON CREATE SET lc.name = o.display + ' (LOINC ' + o.code + ')',
                lc.longCommonName = o.display
MERGE (obs)-[:CODED_BY]->(lc);

// ── 4. Studies, who conducts them, enrolment per quarter ────────────────────
UNWIND [
  {id: 'STUDY-CARDIO-2024', name: 'European Cardiovascular Risk Study', inst: 'did:web:pharmaco.de:research', status: 'open', dataNeeded: 'FHIR Conditions, Observations (blood pressure, cholesterol), Medications', countries: ['DE', 'NL', 'FR', 'ES'], ethics: 'EK-Berlin-2024-0041', participants: 4821},
  {id: 'STUDY-DIAB-2023', name: 'T2D Progression Biomarkers', inst: 'did:web:irs.fr:hdab', status: 'open', dataNeeded: 'OMOP Drug Exposures, Condition Occurrences, Measurements (HbA1c, eGFR)', countries: ['FR', 'DE', 'BE'], ethics: 'CPP-IDF-2023-0178', participants: 2103},
  {id: 'STUDY-RESP-2025', name: 'Respiratory EHDS Cohort', inst: 'did:web:medreg.de:hdab', status: 'recruiting', dataNeeded: 'FHIR Conditions (asthma, COPD), Observation spirometry values', countries: ['DE', 'AT', 'CH'], ethics: 'MedReg-EK-2025-0022', participants: 890}
] AS s
MERGE (st:ResearchStudy {studyId: s.id})
SET st.name = s.name,
    st.studyName = s.name,
    st.institutionDid = s.inst,
    st.purpose = 'secondary-use',
    st.ehdsArticle = 'Art. 53(1)(e)',
    st.status = s.status,
    st.dataNeeded = s.dataNeeded,
    st.countries = s.countries,
    st.ethicsApproval = s.ethics,
    st.participantCount = s.participants,
    st.fictional = true
WITH st, s
MATCH (inst:Participant {participantId: s.inst})
MERGE (inst)-[:CONDUCTS]->(st);

UNWIND [
  {id: 'STUDY-CARDIO-2024:2024-06-30', study: 'STUDY-CARDIO-2024', at: '2024-06-30', participants: 600},
  {id: 'STUDY-CARDIO-2024:2024-09-30', study: 'STUDY-CARDIO-2024', at: '2024-09-30', participants: 1100},
  {id: 'STUDY-CARDIO-2024:2024-12-31', study: 'STUDY-CARDIO-2024', at: '2024-12-31', participants: 1500},
  {id: 'STUDY-CARDIO-2024:2025-03-31', study: 'STUDY-CARDIO-2024', at: '2025-03-31', participants: 2100},
  {id: 'STUDY-CARDIO-2024:2025-06-30', study: 'STUDY-CARDIO-2024', at: '2025-06-30', participants: 2700},
  {id: 'STUDY-CARDIO-2024:2025-09-30', study: 'STUDY-CARDIO-2024', at: '2025-09-30', participants: 3300},
  {id: 'STUDY-CARDIO-2024:2025-12-31', study: 'STUDY-CARDIO-2024', at: '2025-12-31', participants: 3900},
  {id: 'STUDY-CARDIO-2024:2026-03-31', study: 'STUDY-CARDIO-2024', at: '2026-03-31', participants: 4400},
  {id: 'STUDY-CARDIO-2024:2026-06-30', study: 'STUDY-CARDIO-2024', at: '2026-06-30', participants: 4700},
  {id: 'STUDY-CARDIO-2024:2026-09-23', study: 'STUDY-CARDIO-2024', at: '2026-09-23', participants: 4821},
  {id: 'STUDY-DIAB-2023:2024-06-30', study: 'STUDY-DIAB-2023', at: '2024-06-30', participants: 400},
  {id: 'STUDY-DIAB-2023:2024-09-30', study: 'STUDY-DIAB-2023', at: '2024-09-30', participants: 800},
  {id: 'STUDY-DIAB-2023:2024-12-31', study: 'STUDY-DIAB-2023', at: '2024-12-31', participants: 1100},
  {id: 'STUDY-DIAB-2023:2025-03-31', study: 'STUDY-DIAB-2023', at: '2025-03-31', participants: 1400},
  {id: 'STUDY-DIAB-2023:2025-06-30', study: 'STUDY-DIAB-2023', at: '2025-06-30', participants: 1700},
  {id: 'STUDY-DIAB-2023:2025-09-30', study: 'STUDY-DIAB-2023', at: '2025-09-30', participants: 1900},
  {id: 'STUDY-DIAB-2023:2025-12-31', study: 'STUDY-DIAB-2023', at: '2025-12-31', participants: 2000},
  {id: 'STUDY-DIAB-2023:2026-03-31', study: 'STUDY-DIAB-2023', at: '2026-03-31', participants: 2080},
  {id: 'STUDY-DIAB-2023:2026-06-30', study: 'STUDY-DIAB-2023', at: '2026-06-30', participants: 2100},
  {id: 'STUDY-DIAB-2023:2026-09-23', study: 'STUDY-DIAB-2023', at: '2026-09-23', participants: 2103},
  {id: 'STUDY-RESP-2025:2024-06-30', study: 'STUDY-RESP-2025', at: '2024-06-30', participants: 0},
  {id: 'STUDY-RESP-2025:2024-09-30', study: 'STUDY-RESP-2025', at: '2024-09-30', participants: 0},
  {id: 'STUDY-RESP-2025:2024-12-31', study: 'STUDY-RESP-2025', at: '2024-12-31', participants: 0},
  {id: 'STUDY-RESP-2025:2025-03-31', study: 'STUDY-RESP-2025', at: '2025-03-31', participants: 0},
  {id: 'STUDY-RESP-2025:2025-06-30', study: 'STUDY-RESP-2025', at: '2025-06-30', participants: 0},
  {id: 'STUDY-RESP-2025:2025-09-30', study: 'STUDY-RESP-2025', at: '2025-09-30', participants: 0},
  {id: 'STUDY-RESP-2025:2025-12-31', study: 'STUDY-RESP-2025', at: '2025-12-31', participants: 120},
  {id: 'STUDY-RESP-2025:2026-03-31', study: 'STUDY-RESP-2025', at: '2026-03-31', participants: 340},
  {id: 'STUDY-RESP-2025:2026-06-30', study: 'STUDY-RESP-2025', at: '2026-06-30', participants: 610},
  {id: 'STUDY-RESP-2025:2026-09-23', study: 'STUDY-RESP-2025', at: '2026-09-23', participants: 890}
] AS e
MATCH (st:ResearchStudy {studyId: e.study})
MERGE (en:StudyEnrolment {enrolmentId: e.id})
SET en.asOf = date(e.at),
    en.participants = e.participants,
    en.studyId = e.study
MERGE (st)-[:HAS_ENROLMENT]->(en);

// ── 5. The patient's consents (Art. 71 opt-out state per study) ─────────────
MATCH (p:Patient {resourceId: 'P1'})
UNWIND [
  {id: 'CONSENT-001', study: 'STUDY-CARDIO-2024', at: '2024-03-10T09:00:00Z', scope: 'FHIR Conditions + Observations', tc: 'MedReg DE Trust Centre', revokedAt: null},
  {id: 'CONSENT-002', study: 'STUDY-DIAB-2023', at: '2023-11-15T14:30:00Z', scope: 'OMOP Drug Exposures + Conditions', tc: 'Limburg Trust Centre NL', revokedAt: null},
  {id: 'CONSENT-003', study: 'STUDY-RESP-2025', at: '2026-01-12T10:00:00Z', scope: 'FHIR Conditions + spirometry Observations', tc: 'MedReg DE Trust Centre', revokedAt: '2026-05-01T08:00:00Z'}
] AS c
MERGE (pc:PatientConsent {consentId: c.id})
SET pc.patientId = 'P1',
    pc.studyId = c.study,
    pc.grantedAt = datetime(c.at),
    pc.revoked = c.revokedAt IS NOT NULL,
    pc.revokedAt = CASE WHEN c.revokedAt IS NULL THEN null ELSE datetime(c.revokedAt) END,
    pc.purpose = 'secondary-use',
    pc.dataScope = c.scope,
    pc.ehdsArticle = 'Art. 71',
    pc.fictional = true
MERGE (p)-[:GAVE_CONSENT]->(pc)
WITH pc, c
MATCH (st:ResearchStudy {studyId: c.study})
MERGE (pc)-[:FOR_STUDY]->(st)
WITH pc, c
OPTIONAL MATCH (tc:TrustCenter {name: c.tc})
FOREACH (_ IN CASE WHEN tc IS NOT NULL THEN [1] ELSE [] END | MERGE (pc)-[:RESOLVED_BY]->(tc));

// ── 6. Twelve months of access events (Art. 73(1)(e) log) ───────────────────
// One TransferEvent per access, October 2025 to September 2026, with the
// consumer, provider, dataset, permit and contract the audit page reads.
// PharmaCo's purpose credential expired on 2026-06-20; Limburg's permit was
// issued on 2026-02-20 and has no contract; IRS was refused on 2026-03-01
// and keeps attempting the registry (403).
UNWIND [
  {id: 'te-m-pharmaco-synthea--2025-10-01', ts: '2025-10-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2025-10-02', ts: '2025-10-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-10-03', ts: '2025-10-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-11-01', ts: '2025-11-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2025-11-02', ts: '2025-11-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-11-03', ts: '2025-11-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-11-04', ts: '2025-11-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2025-12-01', ts: '2025-12-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2025-12-02', ts: '2025-12-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-12-03', ts: '2025-12-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2025-12-04', ts: '2025-12-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-01-01', ts: '2026-01-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-01-02', ts: '2026-01-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-01-03', ts: '2026-01-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-01-04', ts: '2026-01-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-02-01', ts: '2026-02-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-02-02', ts: '2026-02-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-02-03', ts: '2026-02-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-02-04', ts: '2026-02-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-02-05', ts: '2026-02-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-03-01', ts: '2026-03-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-03-02', ts: '2026-03-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-03-03', ts: '2026-03-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-03-04', ts: '2026-03-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-03-05', ts: '2026-03-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-03-06', ts: '2026-03-11T13:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3785, dur: 355, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-04-01', ts: '2026-04-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-04-02', ts: '2026-04-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-04-03', ts: '2026-04-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-04-04', ts: '2026-04-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-04-05', ts: '2026-04-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-05-01', ts: '2026-05-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-05-02', ts: '2026-05-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-05-03', ts: '2026-05-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-05-04', ts: '2026-05-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-05-05', ts: '2026-05-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-06-01', ts: '2026-06-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-06-02', ts: '2026-06-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-06-03', ts: '2026-06-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-06-04', ts: '2026-06-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-06-05', ts: '2026-06-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-06-06', ts: '2026-06-11T13:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3785, dur: 355, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-07-01', ts: '2026-07-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-07-02', ts: '2026-07-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-07-03', ts: '2026-07-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-07-04', ts: '2026-07-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-07-05', ts: '2026-07-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-07-06', ts: '2026-07-11T13:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3785, dur: 355, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-07-07', ts: '2026-07-18T16:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125822, dur: 408, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-08-01', ts: '2026-08-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-08-02', ts: '2026-08-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-08-03', ts: '2026-08-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-08-04', ts: '2026-08-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-08-05', ts: '2026-08-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-08-06', ts: '2026-08-11T13:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3785, dur: 355, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-08-07', ts: '2026-08-18T16:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125822, dur: 408, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-09-01', ts: '2026-09-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-09-02', ts: '2026-09-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-09-03', ts: '2026-09-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-09-04', ts: '2026-09-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-09-05', ts: '2026-09-04T10:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 960, dur: 302, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-09-06', ts: '2026-09-11T13:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3785, dur: 355, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /federated/stats', reads: []},
  {id: 'te-m-pharmaco-synthea--2026-09-07', ts: '2026-09-18T16:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125822, dur: 408, ct: 'application/fhir+json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-pharmaco-synthea--2026-09-08', ts: '2026-09-25T09:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 471, dur: 461, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2025-10-01', ts: '2025-10-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2025-11-01', ts: '2025-11-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2025-12-01', ts: '2025-12-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2025-12-02', ts: '2025-12-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-01-01', ts: '2026-01-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-01-02', ts: '2026-01-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-02-01', ts: '2026-02-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-02-02', ts: '2026-02-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-03-01', ts: '2026-03-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-03-02', ts: '2026-03-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-04-01', ts: '2026-04-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-04-02', ts: '2026-04-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-05-01', ts: '2026-05-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-05-02', ts: '2026-05-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-05-03', ts: '2026-05-16T14:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45274, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-06-01', ts: '2026-06-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-06-02', ts: '2026-06-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-06-03', ts: '2026-06-16T14:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45274, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-07-01', ts: '2026-07-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-07-02', ts: '2026-07-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-07-03', ts: '2026-07-16T14:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45274, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-08-01', ts: '2026-08-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-08-02', ts: '2026-08-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-08-03', ts: '2026-08-16T14:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45274, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-08-04', ts: '2026-08-23T17:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5611, dur: 249, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-09-01', ts: '2026-09-02T08:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45000, dur: 90, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-09-02', ts: '2026-09-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5337, dur: 143, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-09-03', ts: '2026-09-16T14:15:00Z', ep: '/omop/cohort', m: 'GET', sc: 200, n: 127, b: 45274, dur: 196, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /omop/cohort', reads: []},
  {id: 'te-m-pharmaco-omop-cdm-2026-09-04', ts: '2026-09-23T17:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 12, b: 5611, dur: 249, ct: 'application/json', c: 'did:web:pharmaco.de:research', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:omop-cdm-v54-analytics', permit: 'hdab-decision-medreg-2025-001', contract: 'contract-fhir-t2d-001', purpose: 'SCIENTIFIC_RESEARCH', name: 'PharmaCo Research AG reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-03-01', ts: '2026-03-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-04-01', ts: '2026-04-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-04-02', ts: '2026-04-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-05-01', ts: '2026-05-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-05-02', ts: '2026-05-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-06-01', ts: '2026-06-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-06-02', ts: '2026-06-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-06-03', ts: '2026-06-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /federated/stats', reads: []},
  {id: 'te-m-lmc-synthea--2026-07-01', ts: '2026-07-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-07-02', ts: '2026-07-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-07-03', ts: '2026-07-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /federated/stats', reads: []},
  {id: 'te-m-lmc-synthea--2026-08-01', ts: '2026-08-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-08-02', ts: '2026-08-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-08-03', ts: '2026-08-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /federated/stats', reads: []},
  {id: 'te-m-lmc-synthea--2026-08-04', ts: '2026-08-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-09-01', ts: '2026-09-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125000, dur: 90, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-lmc-synthea--2026-09-02', ts: '2026-09-09T11:15:00Z', ep: '/nlq', m: 'POST', sc: 200, n: 1, b: 549, dur: 143, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /nlq', reads: []},
  {id: 'te-m-lmc-synthea--2026-09-03', ts: '2026-09-16T14:15:00Z', ep: '/federated/stats', m: 'GET', sc: 200, n: 2, b: 3374, dur: 196, ct: 'application/json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /federated/stats', reads: []},
  {id: 'te-m-lmc-synthea--2026-09-04', ts: '2026-09-23T17:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 200, n: 42, b: 125411, dur: 249, ct: 'application/fhir+json', c: 'did:web:lmc.nl:clinic', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:synthea-fhir-r4-mvd', permit: 'hdab-irs-lmc-2026-001', contract: null, purpose: 'SCIENTIFIC_RESEARCH', name: 'Limburg Medical Centre reads /fhir/Patient', reads: ['P1']},
  {id: 'te-m-irs-prostate-2026-04-01', ts: '2026-04-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 180, dur: 90, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-06-01', ts: '2026-06-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 180, dur: 90, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-06-02', ts: '2026-06-09T11:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 317, dur: 143, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-07-01', ts: '2026-07-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 180, dur: 90, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-08-01', ts: '2026-08-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 180, dur: 90, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-08-02', ts: '2026-08-09T11:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 317, dur: 143, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-08-03', ts: '2026-08-16T14:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 454, dur: 196, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-09-01', ts: '2026-09-02T08:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 180, dur: 90, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []},
  {id: 'te-m-irs-prostate-2026-09-02', ts: '2026-09-09T11:15:00Z', ep: '/fhir/Patient', m: 'GET', sc: 403, n: 0, b: 317, dur: 143, ct: 'application/json', c: 'did:web:irs.fr:hdab', p: 'did:web:alpha-klinik.de:participant', ds: 'dataset:prostate-cancer-registry', permit: null, contract: null, purpose: 'PUBLIC_HEALTH', name: 'Institut de Recherche Santé is refused: no permit for the registry', reads: []}
] AS e
MERGE (te:TransferEvent {eventId: e.id})
SET te.name = e.name,
    te.endpoint = e.ep,
    te.method = e.m,
    te.timestamp = datetime(e.ts),
    te.statusCode = e.sc,
    te.resultCount = e.n,
    te.responseBytes = e.b,
    te.duration = e.dur,
    te.contentType = e.ct,
    te.protocol = 'HTTP-PULL',
    te.participant = e.c,
    te.consumerDid = e.c,
    te.providerDid = e.p,
    te.datasetId = e.ds,
    te.permitId = e.permit,
    te.contractId = e.contract,
    te.purpose = e.purpose,
    te.errorMessage = CASE WHEN e.sc = 403 THEN 'No data permit covers this access (Art. 61(1))' ELSE null END,
    te.patientIds = e.reads,
    te.demo = true,
    te.monthly = true
FOREACH (pid IN e.reads | MERGE (pat:Patient {resourceId: pid}) MERGE (te)-[:READ]->(pat))
WITH te, e
OPTIONAL MATCH (c:Participant {participantId: e.c})
FOREACH (_ IN CASE WHEN c IS NOT NULL THEN [1] ELSE [] END | MERGE (te)-[:REQUESTED_BY]->(c))
WITH te, e
OPTIONAL MATCH (p:Participant {participantId: e.p})
FOREACH (_ IN CASE WHEN p IS NOT NULL THEN [1] ELSE [] END | MERGE (te)-[:PROVIDED_BY]->(p))
WITH te, e
OPTIONAL MATCH (ds:HealthDataset {datasetId: e.ds})
FOREACH (_ IN CASE WHEN ds IS NOT NULL THEN [1] ELSE [] END | MERGE (te)-[:ACCESSED]->(ds))
WITH te, e
OPTIONAL MATCH (permit:HDABApproval) WHERE e.permit IS NOT NULL AND permit.approvalId = e.permit
FOREACH (_ IN CASE WHEN permit IS NOT NULL THEN [1] ELSE [] END | MERGE (te)-[:UNDER_PERMIT]->(permit))
WITH te, e
OPTIONAL MATCH (ctr:Contract) WHERE e.contract IS NOT NULL AND ctr.contractId = e.contract
FOREACH (_ IN CASE WHEN ctr IS NOT NULL THEN [1] ELSE [] END | MERGE (te)-[:UNDER]->(ctr));

// ── 7. Quality label assessments per quarter (Art. 78) ──────────────────────
// The assessor renews the label while conformance stays in 0.90 to 1.00.
// AlphaKlinik's score has fallen below that band; the label expired.
UNWIND [
  {id: 'qa:clinic-alphaklinik:2024-Q4', period: '2024-Q4', at: '2024-12-31', conformance: 0.95, completeness: 0.9, timeliness: 0.94},
  {id: 'qa:clinic-alphaklinik:2025-Q1', period: '2025-Q1', at: '2025-03-31', conformance: 0.94, completeness: 0.9, timeliness: 0.94},
  {id: 'qa:clinic-alphaklinik:2025-Q2', period: '2025-Q2', at: '2025-06-30', conformance: 0.93, completeness: 0.89, timeliness: 0.93},
  {id: 'qa:clinic-alphaklinik:2025-Q3', period: '2025-Q3', at: '2025-09-30', conformance: 0.92, completeness: 0.89, timeliness: 0.93},
  {id: 'qa:clinic-alphaklinik:2025-Q4', period: '2025-Q4', at: '2025-12-31', conformance: 0.91, completeness: 0.88, timeliness: 0.92},
  {id: 'qa:clinic-alphaklinik:2026-Q1', period: '2026-Q1', at: '2026-03-31', conformance: 0.9, completeness: 0.88, timeliness: 0.92},
  {id: 'qa:clinic-alphaklinik:2026-Q2', period: '2026-Q2', at: '2026-06-30', conformance: 0.89, completeness: 0.87, timeliness: 0.91},
  {id: 'qa:clinic-alphaklinik:2026-Q3', period: '2026-Q3', at: '2026-09-23', conformance: 0.88, completeness: 0.86, timeliness: 0.91}
] AS a
MERGE (qa:QualityAssessment {assessmentId: a.id})
SET qa.period = a.period,
    qa.assessedAt = date(a.at),
    qa.conformance = a.conformance,
    qa.completeness = a.completeness,
    qa.timeliness = a.timeliness,
    qa.renewalBandLow = 0.90,
    qa.renewalBandHigh = 1.00,
    qa.assessor = 'MedReg DE Quality Assessment Unit',
    qa.ehdsArticle = 'Art. 78',
    qa.fictional = true
WITH qa
MATCH (vc:VerifiableCredential {credentialId: 'vc:data-quality-label:clinic-alphaklinik'})
MERGE (vc)-[:HAS_ASSESSMENT]->(qa)
WITH qa
MATCH (ds:HealthDataset {datasetId: 'dataset:synthea-fhir-r4-mvd'})
MERGE (qa)-[:ASSESSES]->(ds);

// ── 8. Repair: a credential past its expiry is not 'active' ────────────────
// The credential fixtures keep status 'active' after expiresAt; anything that
// trusts the flag is wrong (discussion #265). Derive it from the date.
MATCH (vc:VerifiableCredential)
WHERE vc.expiresAt IS NOT NULL AND datetime(toString(vc.expiresAt)) < datetime()
  AND coalesce(vc.status, 'active') = 'active'
SET vc.status = 'expired';

// ── 9. Pin the credential dates the stories rest on ─────────────────────────
// The credential seed dates expiry relative to its run; the overview stories
// need PharmaCo's purpose credential expired on 2026-06-20 (accesses after it)
// and the two quality labels expired on 2026-09-18 (Art. 78 renewal due).
MATCH (vc:VerifiableCredential {credentialId: 'vc:data-processing-purpose:cro-pharmaco'})
SET vc.expiresAt = datetime('2026-06-20T00:06:57Z'), vc.status = 'expired';
MATCH (vc:VerifiableCredential)
WHERE vc.credentialId IN ['vc:data-quality-label:clinic-alphaklinik', 'vc:data-quality-label:clinic-lmc']
SET vc.expiresAt = datetime('2026-09-18T00:06:57Z'), vc.status = 'expired';
