#!/usr/bin/env bash
# Builds Klarbefund signed and installs it on a connected iPhone.
#
# The project file is generated by XcodeGen and is not in git, so every
# regeneration produces a project with no signing team and a build that fails
# with "Signing for MeinBefund requires a development team". The team is not
# in `project.yml` either, because it is account-specific. So it is supplied
# here: from `TEAM_ID` when set, otherwise read from the Apple Distribution
# identity in the login keychain.
set -euo pipefail

cd "$(dirname "$0")/.."

# The generated dictionary must match its TypeScript source before anything
# reaches a phone: an iPhone coding a value one way and the CLI another is the
# failure this monorepo exists to prevent.
(cd ../../services/epa-ingest && npm run --silent generate:swift -- --check >/dev/null)

team="${TEAM_ID:-}"
if [[ -z "$team" ]]; then
  team="$(security find-identity -v -p codesigning |
    sed -n 's/.*"Apple Distribution: .*(\([A-Z0-9]*\))".*/\1/p' | head -1)"
fi
if [[ -z "$team" ]]; then
  echo "No signing team. Set TEAM_ID to your Apple Developer team id." >&2
  exit 1
fi

device="${DEVICE_ID:-}"
if [[ -z "$device" ]]; then
  device="$(xcrun devicectl list devices 2>/dev/null |
    awk '/available \(paired\)/ && /iPhone/ {print $3; exit}')"
fi

# Built for a generic device rather than for this one.
#
# Two reasons. `-destination "id=..."` fails with
#
#   error: Unable to find a destination matching the provided destination
#   specifier
#
# whenever the phone is asleep or off the network, which reads like a bad
# argument and is really an absent phone. And building generically means the
# .app is ready before the phone is, so reconnecting it costs an install
# rather than a rebuild.
derived="${DERIVED_DATA:-$(mktemp -d)}"
echo "building, team $team"
xcodebuild -project MeinBefund.xcodeproj -scheme MeinBefund \
  -destination 'generic/platform=iOS' -derivedDataPath "$derived" \
  DEVELOPMENT_TEAM="$team" -allowProvisioningUpdates build |
  tail -3

if [[ -z "$device" ]]; then
  echo "Built, but no iPhone is reachable: connect one by cable, unlock it," >&2
  echo "or set DEVICE_ID. Re-run to install without rebuilding." >&2
  exit 1
fi

app="$(find "$derived/Build/Products" -maxdepth 2 -name "MeinBefund.app" |
  grep iphoneos | head -1)"
[[ -n "$app" ]] || { echo "no built app found under $derived" >&2; exit 1; }

xcrun devicectl device install app --device "$device" "$app" | tail -2
echo "installed"
