/**
 * Regression tests for neo4j/seed-persona-overview.cypher (discussion #265)
 * and the fixtures generated with it.
 *
 * The seed is the data the four persona overviews are built from: the demo
 * patient's LOINC-coded measurements at AlphaKlinik Berlin, her consents,
 * twelve months of access events per consumer and dataset, quality label
 * assessments per quarter. Generated by
 * scripts/generate-persona-overview-seed.py; these tests pin what the
 * generator must keep producing, whoever edits it next.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "../../../..");
const read = (rel: string) => readFileSync(join(ROOT, rel), "utf-8");

const seed = read("neo4j/seed-persona-overview.cypher");
const seedSh = read("neo4j/seed.sh");
const schema = read("neo4j/init-schema.cypher");

const KNOWN_DIDS = [
  "did:web:alpha-klinik.de:participant",
  "did:web:pharmaco.de:research",
  "did:web:medreg.de:hdab",
  "did:web:lmc.nl:clinic",
  "did:web:irs.fr:hdab",
];

/** Real organisations that must never appear in demo data (code-style.md). */
const FORBIDDEN = [
  "Charité",
  "Charite",
  "Bayer",
  "BfArM",
  "Zuyderland",
  "INSERM",
  "gematik",
  "rki.de",
  "rivm.nl",
];

const LOINC_CODES = [
  "4548-4",
  "2339-0",
  "2089-1",
  "2093-3",
  "8480-6",
  "8462-4",
  "39156-5",
  "33914-3",
];

describe("seed-persona-overview.cypher", () => {
  it("is idempotent: MERGE only, no bare CREATE", () => {
    expect(seed).not.toMatch(/^\s*CREATE\s+\(/m);
    expect(seed).toMatch(/MERGE \(p:Patient \{resourceId: 'P1'\}\)/);
  });

  it("names only fictional organisations", () => {
    for (const name of FORBIDDEN) {
      expect(seed, `real organisation "${name}" in the seed`).not.toContain(
        name,
      );
    }
    expect(seed).toContain("AlphaKlinik Berlin");
  });

  it("seeds 48 observations: 8 LOINC parameters at 6 visits, with reference ranges", () => {
    const ids = seed.match(/\{id: 'obs-p1-[^']+'/g) ?? [];
    expect(ids).toHaveLength(48);
    for (const code of LOINC_CODES) {
      const perCode = ids.filter((s) => s.includes(`obs-p1-${code}-`));
      expect(perCode, `visits for LOINC ${code}`).toHaveLength(6);
    }
    expect(seed).toContain("obs.referenceLow = o.low");
    expect(seed).toContain("obs.referenceHigh = o.high");
    expect(seed).toContain("MERGE (p)-[:HAS_OBSERVATION]->(obs)");
    expect(seed).toContain("MERGE (obs)-[:CODED_BY]->(lc)");
  });

  it("links the patient to the holder, her record and her consents", () => {
    expect(seed).toContain("MERGE (p)-[:TREATED_AT]->(holder)");
    expect(seed).toContain("MERGE (p)-[:HAS_CONDITION]->(cond)");
    expect(seed).toContain("MERGE (p)-[:HAS_MEDICATION_REQUEST]->(med)");
    expect(seed).toContain("MERGE (p)-[:GAVE_CONSENT]->(pc)");
    expect(seed).toContain("MERGE (pc)-[:FOR_STUDY]->(st)");
    expect(seed.match(/\{id: 'cond-p1-/g)).toHaveLength(8);
    expect(seed.match(/\{id: 'med-p1-/g)).toHaveLength(4);
    expect(seed.match(/\{id: 'CONSENT-\d+'/g)).toHaveLength(3);
    // one consent is withdrawn: the Art. 71 opt-out state
    expect(seed).toMatch(/CONSENT-003[^\n]*revokedAt: '2026-05-01/);
    expect(seed).toContain("pc.revoked = c.revokedAt IS NOT NULL");
  });

  it("seeds the three studies, who conducts them, and ten enrolment points each", () => {
    expect(seed).toContain("MERGE (inst)-[:CONDUCTS]->(st)");
    expect(seed).toContain("MERGE (st)-[:HAS_ENROLMENT]->(en)");
    for (const study of [
      "STUDY-CARDIO-2024",
      "STUDY-DIAB-2023",
      "STUDY-RESP-2025",
    ]) {
      const points = seed.match(new RegExp(`\\{id: '${study}:\\d{4}-`, "g"));
      expect(points, `enrolment for ${study}`).toHaveLength(10);
    }
  });

  it("seeds twelve months of access events with a known consumer and provider each", () => {
    const rows = seed.match(/\{id: 'te-m-[^\n]+/g) ?? [];
    expect(rows.length).toBeGreaterThanOrEqual(100);
    const months = new Set(rows.map((r) => r.match(/ts: '(\d{4}-\d{2})/)![1]));
    expect([...months].sort()).toEqual([
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05",
      "2026-06",
      "2026-07",
      "2026-08",
      "2026-09",
    ]);
    for (const r of rows) {
      const consumer = r.match(/ c: '([^']+)'/)![1];
      const provider = r.match(/ p: '([^']+)'/)![1];
      expect(KNOWN_DIDS, `consumer ${consumer}`).toContain(consumer);
      expect(KNOWN_DIDS, `provider ${provider}`).toContain(provider);
    }
  });

  it("refused attempts carry 403, no permit and the Art. 61(1) reason", () => {
    const refused = (
      seed.match(/\{id: 'te-m-[^\n]+sc: 403[^\n]+/g) ?? []
    ).filter(Boolean);
    expect(refused.length).toBeGreaterThan(0);
    for (const r of refused) {
      expect(r).toContain("c: 'did:web:irs.fr:hdab'");
      expect(r).toContain("permit: null");
      expect(r).toContain("n: 0");
    }
    expect(seed).toContain("No data permit covers this access (Art. 61(1))");
    // Limburg's accesses are served under a permit but without a contract.
    const lmc = seed.match(/\{id: 'te-m-lmc-[^\n]+/g) ?? [];
    expect(lmc.length).toBeGreaterThan(0);
    for (const r of lmc) {
      expect(r).toContain("permit: 'hdab-irs-lmc-2026-001'");
      expect(r).toContain("contract: null");
    }
  });

  it("records which accesses read the patient's record (Art. 8)", () => {
    const reads = seed.match(/reads: \['P1'\]/g) ?? [];
    expect(reads.length).toBeGreaterThan(10);
    expect(seed).toContain("MERGE (te)-[:READ]->(pat)");
    // only served FHIR reads touch a record; refused attempts never do
    const refusedWithReads = seed.match(/sc: 403[^\n]*reads: \['P1'\]/g) ?? [];
    expect(refusedWithReads).toHaveLength(0);
  });

  it("attaches the events to consumer, provider, dataset, permit and contract", () => {
    for (const rel of [
      "REQUESTED_BY",
      "PROVIDED_BY",
      "ACCESSED",
      "UNDER_PERMIT",
      "UNDER",
    ]) {
      expect(seed).toContain(`MERGE (te)-[:${rel}]->`);
    }
  });

  it("seeds eight quarterly quality assessments on the holder's label", () => {
    expect(seed.match(/\{id: 'qa:clinic-alphaklinik:\d{4}-Q\d'/g)).toHaveLength(
      8,
    );
    expect(seed).toContain("MERGE (vc)-[:HAS_ASSESSMENT]->(qa)");
    expect(seed).toContain("MERGE (qa)-[:ASSESSES]->(ds)");
  });

  it("marks expired credentials as expired instead of trusting the flag", () => {
    expect(seed).toMatch(/SET vc\.status = 'expired'/);
  });

  it("cites adopted article numbers only", () => {
    // Proposal-era numbers the discussion asked to retire (Art. 46, 50, 51).
    expect(seed).not.toMatch(/Art\. (46|50|51)\b/);
    for (const article of [
      "Art. 71",
      "Art. 78",
      "Art. 61(1)",
      "Art. 73(1)(e)",
    ]) {
      expect(seed).toContain(article);
    }
  });
});

describe("wiring of the seed", () => {
  it("seed.sh runs the file on the full path and on the demo-only path, after the compliance matrix", () => {
    const runs = seedSh.match(
      /run_file \/seed\/seed-persona-overview\.cypher/g,
    );
    expect(runs).toHaveLength(2);
    const full = seedSh.lastIndexOf("seed-persona-overview.cypher");
    const matrix = seedSh.lastIndexOf("seed-compliance-matrix.cypher");
    expect(full).toBeGreaterThan(matrix);
  });

  it("init-schema.cypher declares the new labels' constraints", () => {
    expect(schema).toContain(
      "FOR (rs:ResearchStudy) REQUIRE rs.studyId IS UNIQUE",
    );
    expect(schema).toContain(
      "FOR (se:StudyEnrolment) REQUIRE se.enrolmentId IS UNIQUE",
    );
    expect(schema).toContain(
      "FOR (qa:QualityAssessment) REQUIRE qa.assessmentId IS UNIQUE",
    );
  });
});

describe("fixtures generated with the seed", () => {
  const bundle = JSON.parse(read("ui/public/mock/patient_observations.json"));
  const poc = JSON.parse(
    read("ui/public/poc/persona-3d/data/observations-p1.json"),
  );

  it("the mock fixture and the prototype bundle are the same document", () => {
    expect(bundle).toEqual(poc);
  });

  it("is a FHIR R4 searchset of 48 fictional Observations for Patient/P1", () => {
    expect(bundle.resourceType).toBe("Bundle");
    expect(bundle.type).toBe("searchset");
    expect(bundle.total).toBe(48);
    expect(bundle.entry).toHaveLength(48);
    expect(bundle.meta.tag[0].code).toBe("fictional");
    for (const { resource } of bundle.entry) {
      expect(resource.resourceType).toBe("Observation");
      expect(resource.subject.reference).toBe("Patient/P1");
      expect(resource.code.coding[0].system).toBe("http://loinc.org");
      expect(LOINC_CODES).toContain(resource.code.coding[0].code);
      expect(typeof resource.valueQuantity.value).toBe("number");
      expect(resource.referenceRange[0].low.value).toBeDefined();
      expect(resource.referenceRange[0].text).toContain("as printed");
      expect(resource.performer[0].display).toContain("fictional");
    }
  });

  it("every observation in the bundle is in the seed under the same id", () => {
    for (const { resource } of bundle.entry) {
      expect(seed).toContain(`{id: '${resource.id}'`);
    }
  });

  it("the prototype's monthly series agree across personas", () => {
    const hdab = JSON.parse(
      read("ui/public/poc/persona-3d/data/hdab-series.json"),
    );
    const hospital = JSON.parse(
      read("ui/public/poc/persona-3d/data/hospital-series.json"),
    );
    const by = (doc: { items: { match: string; series: unknown }[] }) =>
      Object.fromEntries(doc.items.map((i) => [i.match, i.series]));
    const h = by(hdab);
    const p = by(hospital);
    // What the access body sees per consumer is what the holder sees.
    expect(h["p:did:web:pharmaco"]).toEqual(p["c:pharmaco"]);
    expect(h["p:did:web:irs"]).toEqual(p["c:institut"]);
    expect(h["p:did:web:lmc"]).toEqual(p["c:limburg"]);
    expect(h["ds:dataset:synthea"]).toEqual(p["ds:synthea"]);
    expect(hdab.source).toContain("seed-persona-overview.cypher");
  });
});
