"use client";

import { fetchApi } from "@/lib/api";
import { useEffect, useState } from "react";
import { Activity } from "lucide-react";
import PageIntro from "@/components/PageIntro";

interface PatientListItem {
  id: string;
  name: string;
  gender: string;
  birthDate: string;
}

interface CohortStats {
  patients: number;
  encounters: number;
  conditions: number;
  observations: number;
  medications: number;
  procedures: number;
}

interface TimelineEntry {
  fhirType: string;
  fhirId: string;
  date: string;
  display: string;
  omopType: string;
  omopId: string;
}

const FHIR_COLORS: Record<string, string> = {
  Encounter: "#2471A3",
  Condition: "#148F77",
  Observation: "#1E8449",
  MedicationRequest: "#CA6F1E",
  Procedure: "#7D3C98",
};

function StatBadge({ label, value }: { label: string; value?: number }) {
  return (
    <div className="bg-[var(--surface-2)] rounded px-3 py-2 text-center">
      <div className="text-lg font-semibold text-white">
        {value != null ? value.toLocaleString() : "—"}
      </div>
      <div className="text-xs text-[var(--text-secondary)] mt-0.5">{label}</div>
    </div>
  );
}

export default function PatientPage() {
  const [patients, setPatients] = useState<PatientListItem[]>([]);
  const [stats, setStats] = useState<CohortStats | null>(null);
  const [selected, setSelected] = useState<string>("");
  const [timeline, setTimeline] = useState<TimelineEntry[]>([]);
  const [loading, setLoading] = useState(true);
  // When true, the API returned restricted=true (PATIENT role — own record only)
  const [restricted, setRestricted] = useState(false);

  // Load patient list + cohort stats on mount
  useEffect(() => {
    fetchApi("/api/patient")
      .then((r) => r.json())
      .then((d) => {
        setPatients(d.patients ?? []);
        setStats(d.stats ?? null);
        setRestricted(d.restricted === true);
        // Auto-select the only patient when restricted (PATIENT role)
        if (d.restricted && d.patients?.length === 1) {
          setSelected(d.patients[0].id);
        }
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  // Load timeline when patient changes
  useEffect(() => {
    if (!selected) return;
    setLoading(true);
    fetchApi(`/api/patient?patientId=${encodeURIComponent(selected)}`)
      .then((r) => r.json())
      .then((d) => {
        setTimeline(d.timeline ?? []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [selected]);

  const selectedPatient = patients.find((p) => p.id === selected);

  return (
    <div className="min-h-screen bg-[var(--bg)]">
      <div className="max-w-3xl mx-auto px-6 py-10">
        <PageIntro
          title="Patient Journey"
          icon={Activity}
          description="View individual FHIR R4 clinical events mapped to OMOP CDM concepts. Select a patient to see their encounters, conditions, observations, medications, and procedures in chronological order."
          prevStep={{ href: "/catalog", label: "Dataset Catalog" }}
          nextStep={{ href: "/analytics", label: "OMOP Analytics" }}
          infoText="Patient data is generated by Synthea and loaded into Neo4j as FHIR R4 resources. The OMOP CDM mapping (Layer 4) enables cross-site cohort analysis under EHDS Art. 53."
          docLink={{ href: "/docs/architecture", label: "Architecture Docs" }}
        />

        {/* Cohort stats */}
        {stats && (
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 mb-8">
            <StatBadge label="Patients" value={stats.patients} />
            <StatBadge label="Encounters" value={stats.encounters} />
            <StatBadge label="Conditions" value={stats.conditions} />
            <StatBadge label="Observations" value={stats.observations} />
            <StatBadge label="Medications" value={stats.medications} />
            <StatBadge label="Procedures" value={stats.procedures} />
          </div>
        )}

        {/* Patient selector — hidden for PATIENT role (they only see their own record) */}
        {restricted ? (
          <div className="mb-4 px-3 py-2 bg-teal-900/30 border border-teal-700/50 rounded text-sm text-teal-200">
            Showing your personal health record (EHDS Art. 3 / GDPR Art. 15)
          </div>
        ) : (
          <select
            value={selected}
            onChange={(e) => setSelected(e.target.value)}
            className="mb-4 px-3 py-2 bg-[var(--surface-2)] border border-gray-600 rounded text-sm outline-none focus:border-layer3 w-full"
          >
            <option value="">
              — select patient ({patients.length} loaded) —
            </option>
            {patients.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name ?? p.id}
              </option>
            ))}
          </select>
        )}

        {/* Patient demographics */}
        {selectedPatient && (
          <div className="flex gap-4 text-xs text-[var(--text-secondary)] mb-6">
            <span>
              <span className="text-[var(--text-secondary)]">Gender:</span>{" "}
              {selectedPatient.gender ?? "—"}
            </span>
            <span>
              <span className="text-[var(--text-secondary)]">Born:</span>{" "}
              {selectedPatient.birthDate ?? "—"}
            </span>
            <span>
              <span className="text-[var(--text-secondary)]">Events:</span>{" "}
              {timeline.length}
            </span>
          </div>
        )}

        {loading && <p className="text-[var(--text-secondary)]">Loading…</p>}

        {!loading && selected && timeline.length === 0 && (
          <p className="text-[var(--text-secondary)]">
            No timeline events found for this patient.
          </p>
        )}

        {timeline.length > 0 && (
          <ol className="relative border-l border-[var(--border)] space-y-6 pl-6">
            {timeline.map((e, i) => (
              <li key={i} className="relative">
                <span
                  className="absolute -left-[25px] w-4 h-4 rounded-full border-2 border-gray-950"
                  style={{
                    background: FHIR_COLORS[e.fhirType] ?? "#888",
                  }}
                />
                <div className="text-xs text-[var(--text-secondary)] mb-0.5">
                  {e.date ?? "—"}
                </div>
                <div className="font-medium text-sm">
                  <span style={{ color: FHIR_COLORS[e.fhirType] ?? "#888" }}>
                    {e.fhirType}
                  </span>{" "}
                  {e.display ? (
                    <span className="text-gray-200">{e.display}</span>
                  ) : (
                    <span className="text-[var(--text-secondary)] font-mono text-xs">
                      {e.fhirId}
                    </span>
                  )}
                </div>
                {e.omopType && (
                  <div className="text-xs text-layer4 mt-0.5">
                    ↳ OMOP {e.omopType}: {e.omopId}
                  </div>
                )}
              </li>
            ))}
          </ol>
        )}
      </div>
    </div>
  );
}
