#!/usr/bin/env bash
# Phase 6: Post-deployment — seed Neo4j, bootstrap Vault, import Keycloak realm.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${SCRIPT_DIR}/env.sh"
eval "$(get_aca_fqdns)"

log "Phase 6: Post-deployment setup"

az acr login --name "$ACR_NAME"
ACR_PASSWORD=$(az acr credential show --name "$ACR_NAME" --query "passwords[0].value" -o tsv)

# ── Postgres databases (Flexible Server, ADR-041) ───────────────────────────
# This used to `az containerapp exec` psql into mvhd-postgres, which needed a
# TTY and silently created nothing in CI for months. The databases now live on
# Flexible Server, where `az postgres flexible-server db create` is plain ARM:
# no TTY, no exec, and phase 2 reads each one back.
"${SCRIPT_DIR}/13-postgres-flexible-server.sh" 2
ok "Postgres databases ensured on ${PG_FLEX_NAME}"

# ── Build and run Neo4j seed job ─────────────────────────────────────────────
log "Building Neo4j seed image..."
SEED_DIR=$(mktemp -d)
cp "${REPO_ROOT}"/neo4j/*.cypher "${SEED_DIR}/"
cp "${REPO_ROOT}/neo4j/seed.sh" "${SEED_DIR}/seed.sh"

cat > "${SEED_DIR}/Dockerfile" <<'DOCKERFILE'
# neo4j:5-community bundles cypher-shell at /var/lib/neo4j/bin — required by
# seed.sh (Bolt-based loader). A plain alpine base has no cypher-shell and
# silently drops every run_file call, leaving compliance/participants empty.
FROM neo4j:5-community
USER root
RUN apt-get update && apt-get install -y --no-install-recommends bash curl jq \
    && rm -rf /var/lib/apt/lists/*
COPY *.cypher /seed/
COPY seed.sh /seed/seed.sh
RUN chmod +x /seed/seed.sh \
    && ln -sf /var/lib/neo4j/bin/cypher-shell /usr/local/bin/cypher-shell
ENTRYPOINT ["/bin/bash", "/seed/seed.sh"]
DOCKERFILE

docker buildx build --platform linux/amd64 \
  -t "${ACR_LOGIN_SERVER}/mvhd-neo4j-seed:latest" --push "${SEED_DIR}"
rm -rf "${SEED_DIR}"
ok "Neo4j seed image pushed"

# NEO4J_HOST must be the short app name, not the internal FQDN. ACA TCP ingress
# only routes environment-local Bolt via the service short name; the
# *.internal.<domain> FQDN used for HTTP ingress silently times out on TCP.
log "Creating/updating Neo4j seed job..."
if az containerapp job show --name "$NEO4J_SEED_JOB" --resource-group "$RG" -o none 2>/dev/null; then
  az containerapp job update \
    --name "$NEO4J_SEED_JOB" --resource-group "$RG" \
    --image "${ACR_LOGIN_SERVER}/mvhd-neo4j-seed:latest" \
    --cpu 0.5 --memory 1Gi \
    --replica-timeout 3600 \
    --set-env-vars \
      "NEO4J_HOST=${NEO4J_APP}" \
      "NEO4J_PORT=7687" \
      "NEO4J_USER=${NEO4J_USER}" \
      "NEO4J_PASSWORD=${NEO4J_PASSWORD}" \
    -o none
  ok "Neo4j seed job updated"
else
  az containerapp job create \
    --name "$NEO4J_SEED_JOB" --resource-group "$RG" --environment "$ACA_ENV" \
    --image "${ACR_LOGIN_SERVER}/mvhd-neo4j-seed:latest" \
    --registry-server "$ACR_LOGIN_SERVER" \
    --registry-username "$ACR_NAME" \
    --registry-password "$ACR_PASSWORD" \
    --cpu 0.5 --memory 1Gi \
    --trigger-type Manual --replica-timeout 3600 \
    --env-vars \
      "NEO4J_HOST=${NEO4J_APP}" \
      "NEO4J_PORT=7687" \
      "NEO4J_USER=${NEO4J_USER}" \
      "NEO4J_PASSWORD=${NEO4J_PASSWORD}" \
    -o none
  ok "Neo4j seed job created"
fi

log "Starting Neo4j seed job..."
az containerapp job start --name "$NEO4J_SEED_JOB" --resource-group "$RG" -o none
ok "Neo4j seed job started"

# ── Build and run Vault bootstrap job ────────────────────────────────────────
log "Building Vault bootstrap image..."
# The provisioner role binds to this, baked in at build time; see
# keycloak_issuer in env.sh. Refuse to build an image whose role cannot match.
KC_ISSUER=$(keycloak_issuer)
[ -n "$KC_ISSUER" ] || { err "Keycloak's edcv discovery did not answer; cannot bind the provisioner role"; exit 1; }
log "Keycloak issuer: ${KC_ISSUER}"
VAULT_DIR=$(mktemp -d)
cp "${REPO_ROOT}/scripts/vault-init-or-unseal.sh" "${VAULT_DIR}/" 2>/dev/null || true

cat > "${VAULT_DIR}/bootstrap.sh" <<VAULTSCRIPT
#!/bin/sh
# Generated by scripts/azure/06-post-deploy.sh. Mirrors jad/bootstrap-vault.sh,
# the bootstrap the compose stack passes its suites with, on the HTTP API
# because this image has no vault CLI. Every write is checked and the job
# exits non-zero when one fails: the earlier version answered every error with
# a JSON string nobody read, and sent its two policies as the literal body
# '-d', so neither policy ever existed and every agent token carried only
# 'default' (#455, read back from the live Vault on 2026-10-03).
#
# Idempotent. Mounts and roles that exist are kept; keys are written only when
# absent, so a re-run never rotates a key the services already use.
set -eu

VAULT_URL="\${VAULT_ADDR}"
VAULT_TOKEN="\${VAULT_DEV_ROOT_TOKEN_ID:-root}"
KC_URL="\${KEYCLOAK_URL}"
FAILED=0

header() { echo ""; echo "=== \$1 ==="; }

# vault_call METHOD PATH [BODY_FILE]: prints the HTTP status, body in /tmp/resp.json
vault_call() {
  if [ -n "\${3:-}" ]; then
    curl -s -o /tmp/resp.json -w '%{http_code}' -X "\$1" "\${VAULT_URL}/v1\$2" \
      -H "X-Vault-Token: \${VAULT_TOKEN}" -H "Content-Type: application/json" \
      --data @"\$3"
  else
    curl -s -o /tmp/resp.json -w '%{http_code}' -X "\$1" "\${VAULT_URL}/v1\$2" \
      -H "X-Vault-Token: \${VAULT_TOKEN}"
  fi
}

# write METHOD PATH JSON [TEXT]: a 2xx is ok, and so is an error whose body
# contains TEXT (for "path is already in use" on a re-run). Anything else counts.
write() {
  printf '%s' "\$3" > /tmp/body.json
  code=\$(vault_call "\$1" "\$2" /tmp/body.json) || code=000
  case "\$code" in
    2??) echo "  ok    \$1 \$2" ;;
    *)
      if [ -n "\${4:-}" ] && grep -q "\$4" /tmp/resp.json 2>/dev/null; then
        echo "  kept  \$1 \$2 (\$4)"
      else
        echo "  FAIL  \$1 \$2 (HTTP \$code): \$(head -c 300 /tmp/resp.json 2>/dev/null)"
        FAILED=\$((FAILED + 1))
      fi
      ;;
  esac
}

# role NAME JSON: replace a JWT role rather than update it. A POST to an
# existing role changes only the fields it sends and keeps the rest, so the
# participant role kept the bound_audiences ["account"], user_claim sub and
# claim_mappings the first Azure bootstrap gave it (177b773) through every
# later rewrite, and once Vault became persistent (ADR-046) that role was
# what the new participant contexts logged in with. IdentityHub stored no
# participant token, every onboarding failed at the participant context, and
# its log said "invalid audience (aud) claim: audience claim does not match
# any expected audience" (2026-10-03). Delete, then write the whole role.
role() {
  code=\$(vault_call DELETE "/auth/jwt/role/\$1") || code=000
  case "\$code" in
    2??|404) ;;
    *)
      echo "  FAIL  DELETE /auth/jwt/role/\$1 (HTTP \$code)"
      FAILED=\$((FAILED + 1))
      ;;
  esac
  write POST "/auth/jwt/role/\$1" "\$2"
}

# policy NAME HCL
policy() {
  write PUT "/sys/policies/acl/\$1" "\$(jq -n --arg p "\$2" '{policy: \$p}')"
}

# kv_once PATH VALUE: a KV v2 secret with one 'content' field, written only
# when nothing is stored at PATH yet.
kv_once() {
  code=\$(vault_call GET "/secret/data/\$1") || code=000
  if [ "\$code" = 200 ]; then
    echo "  kept  secret/\$1 (present)"
  else
    write POST "/secret/data/\$1" "\$(jq -n --arg c "\$2" '{data: {content: \$c}}')"
  fi
}

header "Wait for an unsealed Vault"
i=0
until [ "\$(vault_call GET /sys/health || true)" = 200 ]; do
  i=\$((i + 1))
  [ "\$i" -lt 36 ] || { echo "  FAIL  Vault not unsealed after 3 min"; exit 1; }
  sleep 5
done
echo "  ok    unsealed"

header "Auth method and mounts"
write POST /sys/auth/jwt '{"type":"jwt"}' "already in use"
write POST /auth/jwt/config "{\"jwks_url\":\"\${KC_URL}/realms/edcv/protocol/openid-connect/certs\",\"default_role\":\"participant\"}"
write POST /sys/mounts/secret '{"type":"kv","options":{"version":"2"}}' "already in use"
write POST /sys/mounts/participants '{"type":"kv","options":{"version":"2"}}' "already in use"
write POST /sys/mounts/transit '{"type":"transit"}' "already in use"

vault_call GET /sys/auth >/dev/null || true
ACCESSOR=\$(jq -r '.data["jwt/"].accessor // .["jwt/"].accessor // empty' /tmp/resp.json)
[ -n "\$ACCESSOR" ] || { echo "  FAIL  no accessor for jwt/"; exit 1; }
echo "  ok    jwt accessor \$ACCESSOR"

# Each participant reaches only its own subtree of participants/, keyed on
# the entity alias, which is the participant_context_id claim (user_claim).
header "Participant policy and role"
policy participants-restricted "path \"participants/data/{{identity.entity.aliases.\${ACCESSOR}.name}}/*\" { capabilities = [\"create\",\"read\",\"update\",\"delete\",\"list\"] }
path \"participants/metadata/{{identity.entity.aliases.\${ACCESSOR}.name}}/*\" { capabilities = [\"list\"] }"
role participant '{"role_type":"jwt","user_claim":"participant_context_id","bound_claims":{"role":"participant"},"token_policies":["participants-restricted"],"clock_skew_leeway":60}'

# Read it back: the role this deployment logs participants in with has no
# audience binding, keys on participant_context_id, and grants only the
# participant policy. A stale field here fails every onboarding, silently.
code=\$(vault_call GET /auth/jwt/role/participant) || code=000
if [ "\$code" = 200 ] && jq -e '.data.bound_audiences == null and .data.user_claim == "participant_context_id" and .data.claim_mappings == null and .data.token_policies == ["participants-restricted"]' /tmp/resp.json >/dev/null; then
  echo "  ok    participant role read back as written"
else
  echo "  FAIL  participant role read back (HTTP \$code): \$(jq -c '.data | {bound_audiences, user_claim, claim_mappings, token_policies}' /tmp/resp.json 2>/dev/null)"
  FAILED=\$((FAILED + 1))
fi

# The provisioner role, which this script once created a POLICY for and then
# never a ROLE. jad/bootstrap-vault.sh creates both; Azure had only the policy,
# so every CFM agent that authenticates to Vault died at launch with
#
#   unable to authenticate with JWT: 400 Bad Request:
#   role "provisioner" could not be found
#
# and that is #318's last blocker for the Keycloak and EDC-V agents. Measured
# on the live stack 2026-09-29. Mirrors the local role: matched on the 'role'
# claim the provisioner client carries, keyed on 'azp', with the issuer as
# this deployment presents it. That is the public issuer, expanded here at
# build time, not KC_URL: KC_URL is the internal address this job reaches
# Keycloak on, and no token ever carries it (#455).
#
# The issuer is pinned as bound_claims.iss. A JWT role has no bound_issuer
# field; that one belongs on auth/jwt/config, where it would bind the
# participant role too. Sent on the role, Vault dropped it without an error
# and the live role read back bound_issuer None, so the pin did nothing.
#
# The policy is the local one: everything. The CFM agents write per-participant
# secrets and KV metadata (soft delete); the narrower policy this script meant
# to write would have refused that, and the one it actually wrote was none.
#
# Quote words in here with '' and never with backticks. This is an UNQUOTED
# heredoc (<<VAULTSCRIPT), so a backtick is command substitution even inside a
# comment: two words in this comment used to be backticked, which ran them as
# commands, printed "command not found" on every deploy, and landed in the
# generated bootstrap.sh as empty strings.
header "Provisioner policy and role"
policy provisioner 'path "*" { capabilities = ["create","read","update","delete","list","sudo"] }
path "sys/*" { capabilities = ["create","read","update","delete","list","sudo"] }'
role provisioner "{\"role_type\":\"jwt\",\"user_claim\":\"azp\",\"bound_claims\":{\"role\":\"provisioner\",\"iss\":\"${KC_ISSUER}\"},\"token_policies\":[\"provisioner\"],\"clock_skew_leeway\":60}"

header "Transit keys"
write POST /transit/keys/dataspace-aes '{"type":"aes256-gcm96"}'
write POST /transit/keys/signing-siglet '{"type":"ed25519"}'

# The aliases the EDC services on Azure are configured with
# (04-edc-services.sh). Generated here, never committed: the compose stack's
# values are in the repository and are for local use only.
header "EDC keys (written once)"
kv_once aes-key-alias "\$(head -c 32 /dev/urandom | base64)"
for dp in dataplane-fhir dataplane-omop; do
  code=\$(vault_call GET "/secret/data/\${dp}-private") || code=000
  if [ "\$code" = 200 ]; then
    echo "  kept  secret/\${dp}-private and -public (present)"
  else
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out /tmp/dp-priv 2>/dev/null
    openssl pkey -in /tmp/dp-priv -pubout -out /tmp/dp-pub 2>/dev/null
    kv_once "\${dp}-private" "\$(cat /tmp/dp-priv)"
    kv_once "\${dp}-public" "\$(cat /tmp/dp-pub)"
    rm -f /tmp/dp-priv /tmp/dp-pub
  fi
done

echo ""
if [ "\$FAILED" -ne 0 ]; then
  echo "=== Vault bootstrap FAILED: \$FAILED write(s) refused ==="
  exit 1
fi
echo "=== Vault bootstrap complete ==="
VAULTSCRIPT

cat > "${VAULT_DIR}/Dockerfile" <<'DOCKERFILE'
FROM alpine:3.19
RUN apk add --no-cache curl jq openssl
COPY bootstrap.sh /app/bootstrap.sh
RUN chmod +x /app/bootstrap.sh
ENTRYPOINT ["/bin/sh", "/app/bootstrap.sh"]
DOCKERFILE

# Tag with the commit as well as :latest. ACA caches :latest and will not
# re-pull it on a job start (CLAUDE.md gotcha 6), so a job left pointing at
# :latest keeps running whatever image it first resolved. That is how the
# provisioner JWT role added in b71fe62 could sit on main while every agent
# on Azure still died on the pre-b71fe62 bootstrap. The job below is pointed
# at the immutable tag, so a new build is actually what runs.
VAULT_BOOTSTRAP_TAG="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || date -u +%Y%m%d%H%M%S)"
VAULT_BOOTSTRAP_IMAGE="${ACR_LOGIN_SERVER}/mvhd-vault-bootstrap:${VAULT_BOOTSTRAP_TAG}"
docker buildx build --platform linux/amd64 \
  -t "${VAULT_BOOTSTRAP_IMAGE}" \
  -t "${ACR_LOGIN_SERVER}/mvhd-vault-bootstrap:latest" --push "${VAULT_DIR}"
rm -rf "${VAULT_DIR}"
ok "Vault bootstrap image pushed (${VAULT_BOOTSTRAP_TAG})"

# create fails when the job already exists, so update that case instead of
# leaving a stale image behind.
if az containerapp job show --name "$VAULT_BOOTSTRAP_JOB" --resource-group "$RG" -o none 2>/dev/null; then
  log "Updating Vault bootstrap job to ${VAULT_BOOTSTRAP_TAG}..."
  az containerapp job update \
    --name "$VAULT_BOOTSTRAP_JOB" --resource-group "$RG" \
    --image "$VAULT_BOOTSTRAP_IMAGE" \
    --replica-timeout 300 \
    -o none
  ok "Vault bootstrap job updated"
else
  log "Creating Vault bootstrap job..."
  az containerapp job create \
    --name "$VAULT_BOOTSTRAP_JOB" --resource-group "$RG" --environment "$ACA_ENV" \
    --image "$VAULT_BOOTSTRAP_IMAGE" \
    --registry-server "$ACR_LOGIN_SERVER" \
    --registry-username "$ACR_NAME" \
    --registry-password "$ACR_PASSWORD" \
    --cpu 0.25 --memory 0.5Gi \
    --trigger-type Manual --replica-timeout 300 \
    --env-vars \
      "VAULT_ADDR=${VAULT_URL}" \
      "VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN}" \
      "KEYCLOAK_URL=${KEYCLOAK_INTERNAL_URL}" \
    -o none
  ok "Vault bootstrap job created"
fi

log "Starting Vault bootstrap job..."
az containerapp job start --name "$VAULT_BOOTSTRAP_JOB" --resource-group "$RG" -o none
ok "Vault bootstrap job started"

# ── Import Keycloak realm via Admin REST API ─────────────────────────────────
REALM_FILE="${REPO_ROOT}/jad/keycloak-realm.json"
if [[ -f "$REALM_FILE" ]]; then
  log "Importing Keycloak realm..."

  # Get admin token
  KC_TOKEN=$(curl -sf -X POST "${KEYCLOAK_PUBLIC_URL}/realms/master/protocol/openid-connect/token" \
    -d "client_id=admin-cli" \
    -d "username=${KC_ADMIN_USER}" \
    -d "password=$(kc_admin_password)" \
    -d "grant_type=password" | jq -r '.access_token')

  if [[ -n "$KC_TOKEN" && "$KC_TOKEN" != "null" ]]; then
    # Import realm
    HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" -X POST \
      "${KEYCLOAK_PUBLIC_URL}/admin/realms" \
      -H "Authorization: Bearer ${KC_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "@${REALM_FILE}")

    if [[ "$HTTP_CODE" == "201" || "$HTTP_CODE" == "409" ]]; then
      ok "Keycloak realm imported (${HTTP_CODE})"
    else
      warn "Keycloak realm import returned HTTP ${HTTP_CODE}"
    fi

    # Update client redirect URIs for Azure.
    # This PUT REPLACES the client's whole redirectUris list, so it must be a
    # superset of what jad/keycloak-realm.json ships (localhost + ACA URL +
    # custom domain). Dropping a host here breaks its logins with Keycloak's
    # "Invalid parameter: redirect_uri" page (incident 2026-07-15).
    log "Updating client redirect URIs..."
    CLIENT_ID_INTERNAL=$(curl -sf \
      "${KEYCLOAK_PUBLIC_URL}/admin/realms/edcv/clients?clientId=health-dataspace-ui" \
      -H "Authorization: Bearer ${KC_TOKEN}" | jq -r '.[0].id // empty')

    if [[ -n "$CLIENT_ID_INTERNAL" ]]; then
      REDIRECT_URIS=$(jq -n --arg ui "$UI_PUBLIC_URL" --arg cd "${CUSTOM_DOMAIN:-}" '
        [
          "http://localhost:3000/api/auth/callback/keycloak",
          "http://localhost:3000/*",
          "http://localhost:3003/api/auth/callback/keycloak",
          "http://localhost:3003/*",
          ($ui + "/api/auth/callback/keycloak"),
          ($ui + "/*")
        ]
        + (if $cd != "" then [
            ("https://" + $cd + "/api/auth/callback/keycloak"),
            ("https://" + $cd + "/*")
          ] else [] end)')
      WEB_ORIGINS=$(jq -n --arg ui "$UI_PUBLIC_URL" --arg cd "${CUSTOM_DOMAIN:-}" '
        ["http://localhost:3000", "http://localhost:3003", $ui, "+"]
        + (if $cd != "" then [("https://" + $cd)] else [] end)')

      HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
        "${KEYCLOAK_PUBLIC_URL}/admin/realms/edcv/clients/${CLIENT_ID_INTERNAL}" \
        -H "Authorization: Bearer ${KC_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{\"redirectUris\": ${REDIRECT_URIS}, \"webOrigins\": ${WEB_ORIGINS}}")
      if [[ "$HTTP_CODE" != "204" ]]; then
        echo "ERROR: Keycloak client update failed (HTTP ${HTTP_CODE})" >&2
        exit 1
      fi

      # Verify: read the client back and require the NextAuth callback for
      # every public host. A silent mismatch here is exactly the failure mode
      # that took production login down.
      LIVE_URIS=$(curl -sf \
        "${KEYCLOAK_PUBLIC_URL}/admin/realms/edcv/clients/${CLIENT_ID_INTERNAL}" \
        -H "Authorization: Bearer ${KC_TOKEN}" | jq -r '.redirectUris[]')
      REQUIRED_URIS=("${UI_PUBLIC_URL}/api/auth/callback/keycloak")
      [[ -n "${CUSTOM_DOMAIN:-}" ]] && \
        REQUIRED_URIS+=("https://${CUSTOM_DOMAIN}/api/auth/callback/keycloak")
      for uri in "${REQUIRED_URIS[@]}"; do
        if ! grep -qxF "$uri" <<< "$LIVE_URIS"; then
          echo "ERROR: redirect URI missing after update: ${uri}" >&2
          echo "       Logins on that host will fail with 'Invalid parameter: redirect_uri'." >&2
          exit 1
        fi
      done
      ok "Client redirect URIs updated & verified ($(wc -l <<< "$LIVE_URIS" | tr -d ' ') URIs)"
    else
      echo "ERROR: client health-dataspace-ui not found after realm import" >&2
      exit 1
    fi
  else
    warn "Could not get Keycloak admin token — realm import skipped"
  fi
else
  warn "Realm file not found at ${REALM_FILE} — skipping Keycloak import"
fi

# ── Custom domain binding (ADR-018: ehds.mabu.red) ──────────────────────────
if [[ -n "${CUSTOM_DOMAIN:-}" ]]; then
  log "Preparing custom domain ${CUSTOM_DOMAIN} for ${UI_APP}..."

  UI_FQDN=$(az containerapp show --name "$UI_APP" --resource-group "$RG" \
    --query "properties.configuration.ingress.fqdn" -o tsv)
  VERIFY_ID=$(az containerapp env show --name "$ACA_ENV" --resource-group "$RG" \
    --query "properties.customDomainConfiguration.customDomainVerificationId" -o tsv)

  cat <<DNS

  ╔══════════════════════════════════════════════════════════════════════════╗
  ║  DNS RECORDS REQUIRED at your DNS provider (iwantmyname / mabu.red)      ║
  ╠══════════════════════════════════════════════════════════════════════════╣
  ║  Type   Name          TTL    Value                                       ║
  ║  ────   ─────────     ────   ─────────────────────────────────────────   ║
  ║  CNAME  ehds          3600   ${UI_FQDN}
  ║  TXT    asuid.ehds    3600   ${VERIFY_ID}
  ╚══════════════════════════════════════════════════════════════════════════╝

  Add both records, wait ~5 min for propagation, then press ENTER to continue
  (or Ctrl-C and re-run: scripts/azure/06-post-deploy.sh)...
DNS
  read -r _

  log "Verifying DNS..."
  for i in $(seq 1 12); do
    cname_value=$(dig +short CNAME "${CUSTOM_DOMAIN}" @8.8.8.8 2>/dev/null | head -1)
    txt_value=$(dig +short TXT "asuid.${CUSTOM_DOMAIN}" @8.8.8.8 2>/dev/null | tr -d '"' | head -1)
    if [[ "${cname_value%.}" == "${UI_FQDN}" && "$txt_value" == "$VERIFY_ID" ]]; then
      ok "DNS verified"
      break
    fi
    echo "  attempt ${i}/12: CNAME=${cname_value:-missing} TXT=${txt_value:-missing}"
    sleep 15
  done

  log "Adding hostname ${CUSTOM_DOMAIN} to ${UI_APP}..."
  az containerapp hostname add \
    --name "$UI_APP" --resource-group "$RG" \
    --hostname "$CUSTOM_DOMAIN" -o none || warn "hostname add may have already been run"

  log "Binding managed certificate (may take 5–15 min)..."
  az containerapp hostname bind \
    --name "$UI_APP" --resource-group "$RG" \
    --hostname "$CUSTOM_DOMAIN" \
    --environment "$ACA_ENV" \
    --validation-method CNAME -o none \
    && ok "Managed certificate bound for https://${CUSTOM_DOMAIN}" \
    || warn "hostname bind failed — retry: az containerapp hostname bind --name ${UI_APP} --resource-group ${RG} --hostname ${CUSTOM_DOMAIN} --environment ${ACA_ENV} --validation-method CNAME"

  # Point NEXTAUTH_URL at the custom domain
  log "Updating NEXTAUTH_URL to https://${CUSTOM_DOMAIN}..."
  az containerapp update --name "$UI_APP" --resource-group "$RG" \
    --set-env-vars "NEXTAUTH_URL=https://${CUSTOM_DOMAIN}" -o none

  # Keycloak redirect URIs for the custom domain are set (and verified) in the
  # realm-import section above — no second PUT here: replacing the list again
  # with a smaller set is what previously dropped hosts and broke login.
fi

# ── Summary ──────────────────────────────────────────────────────────────────
log "Post-deployment complete"
echo "  Neo4j seed job:       ${NEO4J_SEED_JOB} (running)"
echo "  Vault bootstrap job:  ${VAULT_BOOTSTRAP_JOB} (running)"
echo "  Keycloak realm:       imported"
if [[ -n "${CUSTOM_DOMAIN:-}" ]]; then
  echo "  Custom domain:        https://${CUSTOM_DOMAIN}"
fi
echo ""
echo "Monitor job progress:"
echo "  az containerapp job execution list --name ${NEO4J_SEED_JOB} --resource-group ${RG}"
echo "  az containerapp job execution list --name ${VAULT_BOOTSTRAP_JOB} --resource-group ${RG}"
