/**
 * Comprehensive tests for the Dataset Catalog (browse) page.
 *
 * Covers: heading, loading state, dataset rendering, empty state,
 * search/filter, card expansion, JSON-LD download, Mermaid diagram modal,
 * API error fallback, and multiple datasets.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

// ── Mocks ────────────────────────────────────────────────────────────
const mockFetchApi = vi.fn();
vi.mock("@/lib/api", () => ({
  fetchApi: (...args: unknown[]) => mockFetchApi(...args),
}));

vi.mock("next/link", () => ({
  default: ({
    href,
    children,
    ...props
  }: {
    href: string;
    children: React.ReactNode;
  }) => (
    <a href={href} {...props}>
      {children}
    </a>
  ),
}));

vi.mock("@/components/MermaidDiagram", () => ({
  default: ({ chart }: { chart: string }) => (
    <div data-testid="mermaid-diagram">{chart}</div>
  ),
}));

import CatalogPage from "@/app/catalog/page";

// ── Helpers ──────────────────────────────────────────────────────────
function mockResponse(data: unknown) {
  return Promise.resolve({ json: () => Promise.resolve(data), ok: true });
}

const sampleDataset = {
  id: "ds-1",
  title: "Synthetic FHIR Patient Cohort",
  description: "A synthetic dataset of ~100 patients generated by Synthea",
  license: "CC-BY-4.0",
  conformsTo: "http://hl7.org/fhir/R4",
  publisher: "AlphaKlinik Berlin",
  theme: "Patient Summary",
  datasetType: "SyntheticData",
  legalBasis: "EHDS-Art53-SecondaryUse",
  recordCount: 100,
};

const secondDataset = {
  id: "ds-2",
  title: "OMOP CDM Condition Data",
  description: "Condition occurrence records transformed to OMOP CDM v5.4",
  license: "CC-BY-SA-4.0",
  conformsTo: "https://ohdsi.github.io/CommonDataModel/",
  publisher: "Limburg Medical Centre",
  theme: "Condition",
  datasetType: "RealWorldData",
  legalBasis: "EHDS-Art53-SecondaryUse",
  recordCount: 5000,
};

beforeEach(() => {
  vi.clearAllMocks();
  // Suppress URL.createObjectURL / revokeObjectURL in jsdom
  globalThis.URL.createObjectURL = vi.fn(() => "blob:mock");
  globalThis.URL.revokeObjectURL = vi.fn();
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ── Tests ────────────────────────────────────────────────────────────
describe("CatalogPage", () => {
  it("renders the page title and description", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(screen.getByText("Dataset Catalog")).toBeInTheDocument();
    });
    expect(
      screen.getByText(/Explore curated FHIR R4 and OMOP datasets/),
    ).toBeInTheDocument();
  });

  it('shows loading state ("Connecting to Neo4j…") before data arrives', async () => {
    // Never resolve — keeps the component in loading state
    mockFetchApi.mockReturnValue(new Promise(() => {}));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(screen.getByText("Connecting to Neo4j…")).toBeInTheDocument();
    });
  });

  it("loads and displays datasets from the API", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    expect(screen.getByText(/AlphaKlinik Berlin/)).toBeInTheDocument();
    expect(screen.getByText(/CC-BY-4.0/)).toBeInTheDocument();
    // Record count is displayed as a plain number in the Samples column
    expect(screen.getAllByText("100").length).toBeGreaterThan(0);
    expect(mockFetchApi).toHaveBeenCalledWith("/api/catalog");
  });

  it('shows empty state ("No datasets match the current filters.") when API returns empty array', async () => {
    // fetchApi returns empty → triggers fallback → fallback also empty
    mockFetchApi.mockReturnValue(mockResponse([]));
    globalThis.fetch = vi.fn().mockResolvedValue({
      json: () => Promise.resolve([]),
      ok: true,
    });

    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("No datasets match the current filters."),
      ).toBeInTheDocument();
    });
  });

  it("filters datasets by title via the search input", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset, secondDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    const search = screen.getByPlaceholderText("Search datasets…");
    await user.type(search, "OMOP");

    expect(screen.getByText("OMOP CDM Condition Data")).toBeInTheDocument();
    expect(
      screen.queryByText("Synthetic FHIR Patient Cohort"),
    ).not.toBeInTheDocument();
  });

  it("filters datasets by theme", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset, secondDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    const search = screen.getByPlaceholderText("Search datasets…");
    await user.type(search, "Condition");

    expect(screen.getByText("OMOP CDM Condition Data")).toBeInTheDocument();
    expect(
      screen.queryByText("Synthetic FHIR Patient Cohort"),
    ).not.toBeInTheDocument();
  });

  it("opens HealthDCAT-AP detail modal via the details button", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    // Detail modal should not be visible yet
    expect(
      screen.queryByText("HealthDCAT-AP Metadata"),
    ).not.toBeInTheDocument();

    // Click the Bookmark details button to open the modal
    await user.click(
      screen.getByRole("button", { name: "View dataset details" }),
    );

    expect(screen.getByText("HealthDCAT-AP Metadata")).toBeInTheDocument();
    expect(screen.getByText("Download DCAT-AP")).toBeInTheDocument();
    expect(screen.getByText("Data Model Diagram")).toBeInTheDocument();
    expect(screen.getByText("View in Graph")).toBeInTheDocument();
  });

  it("closes the detail modal when the Close button is clicked", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    // Open modal via Bookmark details button
    await user.click(
      screen.getByRole("button", { name: "View dataset details" }),
    );
    expect(screen.getByText("HealthDCAT-AP Metadata")).toBeInTheDocument();

    // Close via the Close button in the modal header
    await user.click(screen.getByRole("button", { name: "Close" }));
    expect(
      screen.queryByText("HealthDCAT-AP Metadata"),
    ).not.toBeInTheDocument();
  });

  it("triggers JSON-LD download when Download DCAT-AP is clicked in the modal", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();

    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    // Open the detail modal first via the Bookmark details button
    await user.click(
      screen.getByRole("button", { name: "View dataset details" }),
    );
    await user.click(screen.getByText("Download DCAT-AP"));

    expect(globalThis.URL.createObjectURL).toHaveBeenCalled();
    expect(globalThis.URL.revokeObjectURL).toHaveBeenCalled();
  });

  it("opens the Mermaid ER diagram modal when Data Model Diagram is clicked", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    // Open the detail modal first via the Bookmark details button
    await user.click(
      screen.getByRole("button", { name: "View dataset details" }),
    );
    // Click Data Model Diagram to switch to the diagram modal
    await user.click(screen.getByText("Data Model Diagram"));

    await waitFor(() => {
      expect(screen.getByTestId("mermaid-diagram")).toBeInTheDocument();
    });
    // Modal title includes the dataset title
    expect(screen.getByText(/HealthDCAT-AP Data Model —/)).toBeInTheDocument();
    // The Mermaid chart content should include erDiagram
    expect(screen.getByTestId("mermaid-diagram").textContent).toContain(
      "erDiagram",
    );
  });

  it("falls back to mock data when the API call fails", async () => {
    mockFetchApi.mockReturnValue(Promise.reject(new Error("Network error")));
    globalThis.fetch = vi.fn().mockResolvedValue({
      json: () => Promise.resolve([sampleDataset]),
      ok: true,
    });

    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByRole("heading", { name: "Synthetic FHIR Patient Cohort" }),
      ).toBeInTheDocument();
    });
    expect(globalThis.fetch).toHaveBeenCalledWith("/mock/catalog.json");
  });

  it("renders multiple datasets", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset, secondDataset]));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    expect(screen.getByText("OMOP CDM Condition Data")).toBeInTheDocument();
    expect(screen.getByText(/AlphaKlinik Berlin/)).toBeInTheDocument();
    // shortPublisher() truncates to first 2 words
    expect(screen.getByText(/Limburg Medical/)).toBeInTheDocument();
  });

  it("handles API returning datasets wrapped in an object", async () => {
    mockFetchApi.mockReturnValue(mockResponse({ datasets: [sampleDataset] }));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });
  });

  it("displays legal basis label from LEGAL_BASIS_LABELS map", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(screen.getByText(/EHDS Art\. 53/)).toBeInTheDocument();
    });
  });

  it("shows HealthDCAT-AP Spec link in the detail modal", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    // Open the detail modal via the Bookmark details button
    await user.click(
      screen.getByRole("button", { name: "View dataset details" }),
    );

    expect(screen.getByText("HealthDCAT-AP Spec")).toBeInTheDocument();
  });

  it("shows search input with correct placeholder", async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByPlaceholderText("Search datasets…"),
      ).toBeInTheDocument();
    });
  });

  it('shows "No datasets match the current filters." when filter matches nothing', async () => {
    mockFetchApi.mockReturnValue(mockResponse([sampleDataset]));
    const user = userEvent.setup();
    render(<CatalogPage />);

    await waitFor(() => {
      expect(
        screen.getByText("Synthetic FHIR Patient Cohort"),
      ).toBeInTheDocument();
    });

    const search = screen.getByPlaceholderText("Search datasets…");
    await user.type(search, "zzz_no_match_zzz");

    expect(
      screen.getByText("No datasets match the current filters."),
    ).toBeInTheDocument();
  });
});
