import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import "./globals.css";
import Navigation from "@/components/Navigation";
import DemoPasswordBanner from "@/components/DemoPasswordBanner";
import AuthProvider from "@/components/AuthProvider";

// Resolve the canonical base URL for metadata (og:image, canonical links, etc.).
// - Azure prod:     https://ehds.mabu.red
// - GitHub Pages:   https://ma3u.github.io/MinimumViableHealthDataspacev2
// - Local dev:      http://localhost:3000
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.NEXT_PUBLIC_STATIC_EXPORT === "true"
    ? "https://ma3u.github.io/MinimumViableHealthDataspacev2"
    : "https://ehds.mabu.red");

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "European Health Data Space | Interactive Demo",
  description:
    "Interactive demo of the European Health Data Space (EHDS). Explore FHIR R4 clinical records, OMOP CDM analytics, and DSP contract negotiation across 7 participant roles with 127 synthetic patients.",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: "/favicon.svg",
  },
  openGraph: {
    title: "European Health Data Space | Interactive Demo",
    description:
      "Explore cross-border health data sharing with 7 demo personas, 127 synthetic patients, and 5,300+ knowledge graph nodes. DSP 2025-1, FHIR R4, OMOP CDM, HealthDCAT-AP.",
    url: "/",
    siteName: "EHDS Demo",
    // Image is auto-generated by app/opengraph-image.tsx (edge runtime, 1200×630).
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "European Health Data Space | Interactive Demo",
    description:
      "Explore cross-border health data sharing with 7 demo personas, 127 synthetic patients, and 5,300+ knowledge graph nodes.",
    // Uses app/opengraph-image.tsx automatically via Next.js metadata conventions.
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

// Reading headers() opts the layout into dynamic rendering, which is required
// for the per-request CSP nonce set by middleware.ts to propagate into the HTML
// stream. Without this, Next.js prerenders layout.tsx at build time and the
// nonce never reaches the client — every framework inline script gets blocked
// by 'strict-dynamic'.
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Inline script applies saved theme class before first paint — prevents flash */}
      <head>
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            // Default theme = light. Only applies dark when the user has
            // previously toggled it. Writing 'light' on first visit makes
            // the choice explicit across reloads and prevents
            // prefers-color-scheme from accidentally being honoured later.
            __html: `(function(){try{var t=localStorage.getItem('theme');var dark=t==='dark';document.documentElement.classList.toggle('dark',dark);if(!t)localStorage.setItem('theme','light');}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <a href="#main-content" className="skip-to-content">
            Skip to main content
          </a>
          <Navigation />
          <DemoPasswordBanner />
          <main id="main-content" className="flex-1" role="main">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
