import type { Metadata, Viewport } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";
import DemoPasswordBanner from "@/components/DemoPasswordBanner";
import AuthProvider from "@/components/AuthProvider";

// Resolve the canonical base URL for metadata (og:image, canonical links, etc.).
// - Azure prod:     https://ehds.mabu.red
// - GitHub Pages:   https://ma3u.github.io/MinimumViableHealthDataspacev2
// - Local dev:      http://localhost:3000
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.NEXT_PUBLIC_STATIC_EXPORT === "true"
    ? "https://ma3u.github.io/MinimumViableHealthDataspacev2"
    : "https://ehds.mabu.red");

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "European Health Data Space | Interactive Demo",
  description:
    "Interactive demo of the European Health Data Space (EHDS). Explore FHIR R4 clinical records, OMOP CDM analytics, and DSP contract negotiation across 7 participant roles with 127 synthetic patients.",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: "/favicon.svg",
  },
  openGraph: {
    title: "European Health Data Space | Interactive Demo",
    description:
      "Explore cross-border health data sharing with 7 demo personas, 127 synthetic patients, and 5,300+ knowledge graph nodes. DSP 2025-1, FHIR R4, OMOP CDM, HealthDCAT-AP.",
    url: "/",
    siteName: "EHDS Demo",
    // Image is auto-generated by app/opengraph-image.tsx (edge runtime, 1200×630).
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "European Health Data Space | Interactive Demo",
    description:
      "Explore cross-border health data sharing with 7 demo personas, 127 synthetic patients, and 5,300+ knowledge graph nodes.",
    // Uses app/opengraph-image.tsx automatically via Next.js metadata conventions.
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Inline script applies saved theme class before first paint — prevents flash */}
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');document.documentElement.classList.toggle('dark',t==='dark')}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <a href="#main-content" className="skip-to-content">
            Skip to main content
          </a>
          <Navigation />
          <DemoPasswordBanner />
          <main id="main-content" className="flex-1" role="main">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
